spring:
  application:
    name: payment-service
  data:
    mongodb:
      uri: mongodb+srv://vuongIT333:VIsnxu3vSZqKyVRD@cluster0-vuongdev.btgns93.mongodb.net/Payment-Service?retryWrites=true&w=majority
    redis:
      host: ${HOST_REDIS:localhost}
      port: ${PORT_REDIS:6379}
      connect-timeout: 10000

  jpa:
    hibernate:
      ddl-auto: update
    show_sql: true
  kafka:
    producer:
      bootstrap-servers: ${KAFKA_HOST:localhost}:${KAFKA_PORT:9092}
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.apache.kafka.common.serialization.StringSerializer

server:
  port: 8082
  servlet:
    context-path: /payment

springdoc:
  swagger-ui:
    path: /swagger-ui.html
  api-docs:
    path: /v3/api-docs

jwt:
  expiration: 86400 # 1 day in seconds
  secretKey: TaqlmGv1iEDMRiFp/pHuID1+T84IABfuA0xXh4GhiUI=
  x-internal-token: k118wSpPDIVURys